# Include BoardConfigVendor if exists.
# File doesn't exist. Correct path anyway.
-include vendor/qcom/proprietary/common/msm8660/BoardConfigVendor.mk

# Audio
BOARD_USES_GENERIC_AUDIO := true

# Camera Stub
USE_CAMERA_STUB := true

# HDMI
TARGET_USE_HDMI_AS_PRIMARY := false
ifeq ($(TARGET_USE_HDMI_AS_PRIMARY),true)
    TARGET_HAVE_HDMI_OUT := false
else
    TARGET_HAVE_HDMI_OUT := false
endif # TARGET_USE_HDMI_AS_PRIMARY

TARGET_USES_OVERLAY := true
TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := false
TARGET_NO_RADIOIMAGE := true

# Kernel
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_CPU_ABI  := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
BOARD_KERNEL_BASE    := 0x40200000
BOARD_KERNEL_PAGESIZE := 2048


TARGET_HARDWARE_3D := false
#TARGET_BOARD_PLATFORM := msm8660
#TARGET_BOOTLOADER_BOARD_NAME := MSM8660_SURF
TARGET_AVOID_DRAW_TEXTURE_EXTENSION := true
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USES_UNCOMPRESSED_KERNEL := false
TARGET_USES_LAUNCHER_V1 := true

BOARD_EGL_CFG := device/htc/$(TARGET_PRODUCT)/egl.cfg

# Use signed boot and recovery image
TARGET_BOOTIMG_SIGNED := true

TARGET_USE_SCORPION_BIONIC_OPTIMIZATION := true
TARGET_USE_SCORPION_PLD_SET := true
TARGET_SCORPION_BIONIC_PLDOFFS := 6
TARGET_SCORPION_BIONIC_PLDSIZE := 128
HAVE_CYTTSP_FW_UPGRADE := true

#TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
#TARGET_RECOVERY_UI_LIB := librecovery_ui_qcom

# Add NON-HLOS files for ota upgrade
#ADD_RADIO_FILES ?= false
